### ISSUE TITLE
Change right of .docker folder

### ISSUE THREAD

**Issue by Vincere1st** [inetum-orleans/docker-devbox-wsl#5]
The .docker folder in the home directory has the root right.
It isn't good, wee need to find a solution for change this right to those of the user.

**Comment by jeremyVignelles** [comment]
Removing those lines should be enough to solve the issue. The `docker-compose-plugin` apt package should already install the correct plugin...
https://github.com/inetum-orleans/docker-devbox-wsl/pull/1#discussion_r1553792332

**Comment by Vincere1st** [comment]
Yes , it is the good solution
